# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved. 2021
# SPDX-License-Identifier: Apache-2.0

ALARM_KEY = 'alarm_key'
ATTRIBUTE_PROPERTY_TABLE_NAME = 'attributePropertyTableName'
COMPONENT_NAME = 'componentName'
CONFIGURATION = 'configuration'
ELEMENT_ID = 'elem_id'
END_TIME = 'endTime'
ENTITY_ID = 'entityId'
ENTITY_PROPERTY_REFERENCE = 'entityPropertyReference'
ENTRIES = 'entries'
ENTRY = 'entry'
ENTRY_ID = 'entryId'
ERROR_CODE = 'errorCode'
ERROR_MESSAGE = 'errorMessage'
EXTERNAL_ID = 'externalId'
FILTERS = 'propertyFilters'
FILTER_ALARM_PROPERTY_NAME = 'alarm_status'
FILTER_OPERATOR = 'operator'
FILTER_PROPERTY_NAME = 'propertyName'
FILTER_STRING_VALUE = 'stringValue'
FILTER_VALUE = 'value'
MAX_RESULTS = 'maxResults'
NEXT_TOKEN = 'nextToken'
ORDER_BY_ASC = 'ASC'
ORDER_BY_ASCENDING = 'ASCENDING'
ORDER_BY_DESC = 'DESC'
ORDER_BY_DESCENDING = 'DESCENDING'
ORDER_BY_TIME = 'orderByTime'
PROPERTIES = 'properties'
PROPERTY_DATA_TYPE = 'dataType'
PROPERTY_DEFINITION = 'definition'
PROPERTY_NAME = 'propertyName'
PROPERTY_STRING_VALUE = 'stringValue'
PROPERTY_TYPE = 'type'
PROPERTY_VALUE = 'value'
PROPERTY_VALUES = 'propertyValues'
PROPERTY_VALUE_FILTER = 'propertyValueFilter'
SELECTED_PROPERTIES = 'selectedProperties'
START_TIME = 'startTime'
TABLE_NAME = 'table_name'
TIMESERIES_TABLE_NAME = 'timeseriesTableName'
TIMESTAMP = 'time'
# snowflake write_pandas() internally use Snowflake 'COPY INTO' SQL command which doesn't throw exceptions,
# use 'SnowflakeException' as default ERROR_CODE
UDW_DEFAULT_ERROR_CODE = 'SnowflakeException'
UDW_DEFAULT_ERROR_MESSAGE = 'Failed to load data into Snowfalke'
WORKSPACE_ID = 'workspaceId'

def getOrderByWord(orderBy):
    return ORDER_BY_ASC if orderBy == ORDER_BY_ASC else ORDER_BY_DESC 
